<!--
README: Bluefin Wolves Teaser Landing Page Component
===================================================
- Page Path: projectbluefin.io/wolves
- Comic Content: Delegated to WolvesComicReader.vue. PDF URL is managed
  by the component itself (BASE_URL + color-with-bluefin.pdf).
- Quotes: Sourced from `src/data/bazzite-quotes.json` with fields
  `quote`, `attribution`, optional `context`, and optional `date`.
  Real approved Discord quotes should replace placeholder lorem ipsum values in that file.
- Donate QR Code: Generated by `scripts/generate-qrs.js` and currently points to `#`.
  Replace `donateUrl` in `scripts/generate-qrs.js` and re-run the script when the real URL is ready.
- Playlist ID in use: `PLA78oiE-RGAE` ("Bluefin: Seven Days to the Wolves" on YouTube).
- Playback approach: click-to-start in-page YouTube playlist player + visible YouTube Music deep link.
  We do not attempt auth-state detection because YouTube sign-in/Premium status cannot be reliably verified in-browser.
- Future Spotify support: add a Spotify URI/provider adapter in `src/data/wolves-playlist.json`
  and `WolvesSoundtrack.vue` without redesigning page layout.
-->
<script setup lang="ts">
import type { WolvesChapter } from './data/wolves-story'
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import TopNavbar from './components/TopNavbar.vue'
import WolvesComicReader from './components/wolves/WolvesComicReader.vue'
import WolvesLoreColumn from './components/wolves/WolvesLoreColumn.vue'
import WolvesQrCodes from './components/wolves/WolvesQrCodes.vue'
import WolvesSoundtrack from './components/wolves/WolvesSoundtrack.vue'
import { LangLandingBluefinImageURLs } from './content'
import { wolvesRelease } from './data/wolves-story'

import { getChapterForPage } from './utils/wolvesStory'

// Soundtrack playback and comic autoplay state
const isPlaying = ref(false)

// Current page (1-based) tracked here so the chapter can be passed to WolvesSoundtrack.
const currentPage = ref(1)
const activeChapter = computed<WolvesChapter | undefined>(() => getChapterForPage(currentPage.value))

const loreColumnRef = ref<any>(null)
const isLoreCopied = ref(false)

function handlePrevLore() {
  loreColumnRef.value?.prevLore()
}

function handleNextLore() {
  loreColumnRef.value?.nextLore()
}

function handleShareLore() {
  loreColumnRef.value?.shareLore()
}

function handleCopiedStatus(status: boolean) {
  isLoreCopied.value = status
}

function handleTrackChange(index: number) {
  if (index === 0) {
    currentPage.value = 1
  }
  else if (index === 1) {
    currentPage.value = 6
  }
  else if (index === 6) {
    currentPage.value = 11
  }
}

// Console Email Submission
const emailInput = ref('')
const isSubmittingEmail = ref(false)
const emailSubmitted = ref(false)
const emailFeedback = ref('')

function handleEmailSubmit() {
  if (!emailInput.value || !emailInput.value.includes('@')) {
    emailFeedback.value = 'Error from server (BadRequest): invalid email coordinate'
    return
  }
  isSubmittingEmail.value = true
  emailFeedback.value = 'kubectl rollout status deployment/comms-relay-agent -n bazzite'
  setTimeout(() => {
    isSubmittingEmail.value = false
    emailSubmitted.value = true
    emailFeedback.value = 'deployment "comms-relay-agent" successfully rolled out // CONNECTION SECURED.'
  }, 1500)
}

// Background Wallpaper State
const playlistCurrentTime = ref(0)
const playlistDuration = ref(0)
const playlistTrackIndex = ref(0)
const isSoundtrackActive = ref(false)

function handleProgress(data: { currentTime: number, duration: number, playlistIndex: number }) {
  playlistCurrentTime.value = data.currentTime
  playlistDuration.value = data.duration
  playlistTrackIndex.value = data.playlistIndex
  isSoundtrackActive.value = true
}

const totalProgress = computed(() => {
  if (!isSoundtrackActive.value || playlistDuration.value <= 0) {
    return 0
  }
  const trackProgress = playlistCurrentTime.value / playlistDuration.value
  return Math.min(1, Math.max(0, (playlistTrackIndex.value + trackProgress) / 7))
})

const currentPairIndex = computed(() => {
  if (!isSoundtrackActive.value) {
    return 6 // Start with July (index 6, Month 7) by default
  }
  const wallpaperIndexFloat = totalProgress.value * 12 + 6
  return Math.floor(wallpaperIndexFloat) % 12
})

const nightOpacity = computed(() => {
  if (!isSoundtrackActive.value) {
    return 1.0 // Start with July night by default
  }
  const wallpaperIndexFloat = totalProgress.value * 12 + 6
  const localProgress = wallpaperIndexFloat - Math.floor(wallpaperIndexFloat)
  return Math.sin(localProgress * Math.PI)
})

const activeMonth = ref(6)
const previousMonth = ref<number | null>(null)
const isTransitioning = ref(false)

watch(currentPairIndex, (newVal, oldVal) => {
  if (oldVal !== undefined && newVal !== oldVal) {
    previousMonth.value = oldVal
    activeMonth.value = newVal
    isTransitioning.value = true
    setTimeout(() => {
      previousMonth.value = null
      isTransitioning.value = false
    }, 1500)
  }
  else {
    activeMonth.value = newVal
  }
}, { immediate: true })

function getDayWallpaperUrl(monthIndex: number) {
  const pairStr = String(monthIndex + 1).padStart(2, '0')
  return `url('${import.meta.env.BASE_URL}img/wallpapers/bluefin-${pairStr}-day.webp')`
}

function getNightWallpaperUrl(monthIndex: number) {
  const pairStr = String(monthIndex + 1).padStart(2, '0')
  return `url('${import.meta.env.BASE_URL}img/wallpapers/bluefin-${pairStr}-night.webp')`
}

const isImmersive = ref(false)
const baseUrl = import.meta.env.BASE_URL

const filteredMascots = computed(() => {
  return LangLandingBluefinImageURLs.filter((url) => {
    const filename = url.split('/').pop() || ''
    return !filename.startsWith('aurora') && !filename.includes('jonatan')
  })
})

const mascotIndex = ref(0)
const nextMascotIndex = ref<number | null>(null)
const isMascotTransitioning = ref(false)

let mascotTimer: ReturnType<typeof setInterval> | null = null

function startMascotRotation() {
  if (mascotTimer) {
    return
  }
  mascotTimer = setInterval(() => {
    if (filteredMascots.value.length === 0) {
      return
    }
    const nextIdx = (mascotIndex.value + 1) % filteredMascots.value.length
    nextMascotIndex.value = nextIdx
    isMascotTransitioning.value = true
    setTimeout(() => {
      mascotIndex.value = nextIdx
      nextMascotIndex.value = null
      isMascotTransitioning.value = false
    }, 1000)
  }, 6000)
}

function stopMascotRotation() {
  if (mascotTimer) {
    clearInterval(mascotTimer)
    mascotTimer = null
  }
}

watch(isImmersive, (active) => {
  if (active) {
    startMascotRotation()
  }
  else {
    stopMascotRotation()
  }
})

function enterImmersiveExperience() {
  isImmersive.value = true
  isPlaying.value = true
  if (document.documentElement.requestFullscreen) {
    document.documentElement.requestFullscreen().catch((err) => {
      console.warn('Could not enter fullscreen:', err)
    })
  }
}

function exitImmersiveExperience() {
  isImmersive.value = false
  if (document.fullscreenElement && document.exitFullscreen) {
    document.exitFullscreen().catch((err) => {
      console.warn('Could not exit fullscreen:', err)
    })
  }
}

function handleFullscreenChange() {
  isImmersive.value = !!document.fullscreenElement
}

onMounted(() => {
  document.addEventListener('fullscreenchange', handleFullscreenChange)
})

onBeforeUnmount(() => {
  document.removeEventListener('fullscreenchange', handleFullscreenChange)
  stopMascotRotation()
})
</script>

<template>
  <div class="wolves-teaser-page">
    <!-- Dynamic Wallpaper Background Layers -->
    <div class="wallpaper-container">
      <!-- Previous Month Buffer (fading out) -->
      <div v-if="previousMonth !== null" class="wallpaper-buffer-layer fading-out">
        <div class="wallpaper-layer day-layer" :style="{ backgroundImage: getDayWallpaperUrl(previousMonth) }" />
        <div class="wallpaper-layer night-layer" :style="{ backgroundImage: getNightWallpaperUrl(previousMonth), opacity: nightOpacity }" />
      </div>

      <!-- Active Month Buffer (fading in) -->
      <div class="wallpaper-buffer-layer" :class="{ 'is-transitioning': isTransitioning }">
        <div class="wallpaper-layer day-layer" :style="{ backgroundImage: getDayWallpaperUrl(activeMonth) }" />
        <div class="wallpaper-layer night-layer" :style="{ backgroundImage: getNightWallpaperUrl(activeMonth), opacity: nightOpacity }" />
      </div>
    </div>

    <!-- Top Global Navigation Bar -->
    <TopNavbar v-if="!isImmersive" />

    <!-- Main Outer Container -->
    <div v-if="!isImmersive" class="wolves-layout">
      <!-- SECTION 1: HERO SECTION -->
      <header class="wolves-hero">
        <div class="hero-text">
          <!-- Aggressive display typography with heavy scale -->
          <h1 class="hero-title">
            Seven Days to the <span class="accent">Wolves</span>
          </h1>
          <p class="hero-description">
            In the distant future, open source maintainers are not only sought after, they are hunted. Enslaved by the very machines they created, betrayed by the societies they swore to protect. They fight alone.

            <br><br>Our Childhood's End, is their beginning.

            <br><br>A fundraising effort to immortalize contributors in legend. Issue sponsorships available.
          </p>

          <div class="experience-cta-wrap">
            <button class="experience-cta-btn font-mono" @click="enterImmersiveExperience">
              [ EXPERIENCE SEVEN DAYS TO THE WOLVES ]
            </button>
            <div class="experience-cta-sub font-mono">
              RECOMMENDED: HEADPHONES ON // VOLUME UP
            </div>
          </div>

          <div class="hero-footnote">
            Coming 2027
          </div>
        </div>
      </header>

      <!-- Two-column desktop layout: Comic Reader on the left, a pinned
           Soundtrack Widget + Bazzite Dispatch sidebar on the right. Falls
           back to a single vertical stack below 1024px. -->
      <div class="content-grid">
        <div class="col-left">
          <!-- SECTION 2: COMIC READER -->
          <WolvesComicReader
            :chapters="wolvesRelease.chapters"
            :autoplay="isPlaying"
            @update:page="currentPage = $event"
          />

          <!-- Soundtrack Control Widget (Moved below slides, expanded) -->
          <WolvesSoundtrack
            v-model:playing="isPlaying"
            :chapter="activeChapter"
            :lore-copied="isLoreCopied"
            @track-change="handleTrackChange"
            @prev-lore="handlePrevLore"
            @next-lore="handleNextLore"
            @share-lore="handleShareLore"
            @progress="handleProgress"
          />
        </div>

        <div class="col-right">
          <WolvesLoreColumn
            ref="loreColumnRef"
            :chapter="activeChapter"
            @copied-status="handleCopiedStatus"
          />

          <!-- Decryption Status Meter -->
          <div class="decryption-meter-card">
            <div class="meter-header">
              <span class="meter-title font-mono">DECRYPTION_STATUS // CHAPTER_02</span>
              <span class="meter-percentage font-mono">7%</span>
            </div>
            <div class="meter-bar-container">
              <div class="meter-bar-fill" style="width: 7%" />
            </div>
            <p class="meter-details font-mono">
              Operatives active: 1,337 // Decoding node: PROMETHEUS-7
            </p>
          </div>
        </div>
      </div>

      <!-- SECTION 4: COMMUNITY & CONVERSION (Console + Discord) -->
      <section id="wolves-support" class="comic-reader-section">
        <div class="support-wrap">
          <h2 class="title-h2">
            Establish Secure Channel
          </h2>
          <p class="title-p">
            Subscribe to receive decrypted transmissions and critical notifications when Chapter 1 launches. Or connect to the operative mesh directly on Discord.
          </p>
        </div>

        <div class="community-console-grid">
          <!-- Terminal Newsletter Console -->
          <div class="terminal-console-card">
            <div class="console-header">
              <span class="console-title font-mono">nimbinatus@blue-universal:~</span>
              <div class="gnome-window-controls">
                <button class="gnome-control-btn minimize" aria-label="Minimize" tabindex="-1" type="button">
                  <svg width="12" height="12" viewBox="0 0 12 12"><rect x="2" y="5.5" width="8" height="1" fill="currentColor" /></svg>
                </button>
                <button class="gnome-control-btn maximize" aria-label="Maximize" tabindex="-1" type="button">
                  <svg width="12" height="12" viewBox="0 0 12 12"><rect x="2.5" y="2.5" width="7" height="7" rx="0.5" fill="none" stroke="currentColor" stroke-width="1" /></svg>
                </button>
                <button class="gnome-control-btn close" aria-label="Close" tabindex="-1" type="button">
                  <svg width="12" height="12" viewBox="0 0 12 12"><path d="M2.5 2.5 L9.5 9.5 M9.5 2.5 L2.5 9.5" stroke="currentColor" stroke-width="1" stroke-linecap="round" /></svg>
                </button>
              </div>
            </div>
            <div class="console-body">
              <p class="console-text font-mono text-cyan">
                nimbinatus@blue-universal:~$ kubectl apply -f bazzite-comms.yaml
              </p>
              <p class="console-text font-mono text-green">
                configmap/bazzite-comms-config created
                <br>deployment.apps/comms-relay-agent created
              </p>
              <p class="console-text font-mono text-gray">
                [SYSTEM] Enter operative email to launch deployment:
              </p>

              <form v-if="!emailSubmitted" class="console-form" @submit.prevent="handleEmailSubmit">
                <span class="console-prompt font-mono">&gt;</span>
                <input
                  v-model="emailInput"
                  type="email"
                  placeholder="operative@domain.xyz"
                  class="console-input font-mono"
                  :disabled="isSubmittingEmail"
                  required
                >
                <button
                  type="submit"
                  class="console-submit-btn font-mono"
                  :disabled="isSubmittingEmail"
                >
                  [ APPLY ]
                </button>
              </form>

              <div v-if="emailFeedback" class="console-feedback font-mono" :class="{ success: emailSubmitted }">
                {{ emailFeedback }}
              </div>
            </div>
          </div>

          <!-- Encrypted Discord Invite Card -->
          <div class="discord-invite-card">
            <h3 class="discord-title font-mono">
              [ SECURE_MESH_LINK ]
            </h3>
            <p class="discord-desc">
              Connect to the live mesh. Chat with core maintainers, coordinate Linux workstation factory builds, and decrypt incoming lore with the community.
            </p>
            <div class="discord-action-wrap">
              <a
                href="https://discord.gg/projectbluefin"
                target="_blank"
                rel="noopener noreferrer"
                class="discord-btn"
              >
                JOIN THE MESH (DISCORD) &rarr;
              </a>
              <span class="discord-coords font-mono">COORDS: 42.109 / -83.045 // MESH_ACTIVE</span>
            </div>
          </div>
        </div>

        <div class="support-links font-mono">
          <a href="https://store.projectbluefin.io" target="_blank" rel="noopener noreferrer">STORE_ACCESS</a>
          <span class="separator">|</span>
          <a href="https://docs.projectbluefin.io/donations" target="_blank" rel="noopener noreferrer">DONATE_FUNDS</a>
        </div>
      </section>

      <section class="wolves-page-qr comic-reader-section">
        <WolvesQrCodes />
      </section>
    </div>

    <!-- Immersive Fullscreen Theater Experience -->
    <div v-else class="immersive-layout">
      <!-- TOP STATUS BAR HUD -->
      <header class="immersive-hud-header">
        <div class="hud-left font-mono">
          <span class="hud-indicator-dot animate-pulse-fast" />
          COGNITIVE_CHANNEL_SECURED // SEVEN DAYS TO THE WOLVES
        </div>
        <button class="hud-exit-btn font-mono" @click="exitImmersiveExperience">
          [ EXIT EXPERIENCE ]
        </button>
      </header>

      <!-- MIDDLE CONTENT AREA (WIDESCREEN SPLIT 2fr 1fr) -->
      <div class="immersive-content-grid">
        <div class="immersive-col-left">
          <WolvesComicReader
            :chapters="wolvesRelease.chapters"
            :autoplay="isPlaying"
            @update:page="currentPage = $event"
          />
        </div>

        <div class="immersive-col-right">
          <WolvesLoreColumn
            ref="loreColumnRef"
            :chapter="activeChapter"
            @copied-status="handleCopiedStatus"
          />
        </div>
      </div>

      <!-- BOTTOM CONTROLS HUD -->
      <footer class="immersive-hud-footer">
        <!-- Mascot Rotating Console (circular node) -->
        <div class="mascot-console-hud">
          <div class="mascot-console-ring">
            <div class="mascot-display-area">
              <template v-if="filteredMascots.length > 0">
                <img
                  v-if="nextMascotIndex !== null"
                  :src="`${baseUrl}${filteredMascots[nextMascotIndex].replace('./', '')}`"
                  class="mascot-avatar fading-in"
                  alt="Telemetry Avatar Next"
                >
                <img
                  :src="`${baseUrl}${filteredMascots[mascotIndex].replace('./', '')}`"
                  class="mascot-avatar"
                  :class="{ 'fading-out': isMascotTransitioning }"
                  alt="Telemetry Avatar"
                >
              </template>
            </div>
            <div class="hud-ring-overlay" />
          </div>
          <div class="mascot-telemetry-text font-mono">
            <span>OPERATIVE_CORE</span>
            <span class="text-cyan">FEED: ACTIVE</span>
          </div>
        </div>

        <!-- Soundtrack Dock -->
        <div class="immersive-soundtrack-dock">
          <WolvesSoundtrack
            v-model:playing="isPlaying"
            :chapter="activeChapter"
            :lore-copied="isLoreCopied"
            @track-change="handleTrackChange"
            @prev-lore="handlePrevLore"
            @next-lore="handleNextLore"
            @share-lore="handleShareLore"
            @progress="handleProgress"
          />
        </div>

        <!-- Right telemetry HUD details -->
        <div class="hud-right-telemetry font-mono">
          <div class="decryption-mini-meter">
            <div class="meter-header-mini">
              <span>DECRYPTION // NODE_07</span>
              <span class="text-cyan">7%</span>
            </div>
            <div class="meter-bar-mini">
              <div class="meter-fill-mini" />
            </div>
          </div>
          <div class="hud-telemetry-coords">
            LAT: 42.109 // LON: -83.045
          </div>
        </div>
      </footer>
    </div>
  </div>
</template>

<style scoped lang="scss">
.wallpaper-container {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  overflow: hidden;
  pointer-events: none;
  z-index: 0;
}

.wallpaper-buffer-layer {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  opacity: 1;
  pointer-events: none;

  &.fading-out {
    animation: fadeOutBuffer 1.5s ease-in-out forwards;
    z-index: 1;
  }

  &.is-transitioning {
    z-index: 2;
    animation: fadeInBuffer 1.5s ease-in-out forwards;
  }
}

@keyframes fadeInBuffer {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

@keyframes fadeOutBuffer {
  from {
    opacity: 1;
  }
  to {
    opacity: 0;
  }
}

.wallpaper-layer {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
  pointer-events: none;
}

.day-layer {
  z-index: 1;
}

.night-layer {
  z-index: 2;
  transition: opacity 0.5s ease-in-out;
}

.wolves-teaser-page {
  background-color: #0c1016;
  min-height: 100vh;
  position: relative;
  // Firefox can break sticky descendants when an ancestor creates a scrolling
  // container via overflow. `clip` prevents horizontal bleed without that side
  // effect.
  overflow-x: clip;
  box-sizing: border-box;
}

.wolves-layout {
  position: relative;
  z-index: 3;
  max-width: 1280px;
  margin: 0 auto;
  padding: 32px 24px 80px;
  display: flex;
  flex-direction: column;
  gap: 32px;
}

.wolves-page-qr {
  margin-top: 8px;
}

// Two-column desktop grid: Comic Reader (left) + pinned Soundtrack Widget /
// Bazzite Dispatch sidebar (right). Falls back to a vertical stack below
// 1024px.
.content-grid {
  display: flex;
  flex-direction: column;
  gap: 16px;
  width: 100%;

  @media (min-width: 1024px) {
    display: grid;
    grid-template-columns: 2fr 1fr;
    align-items: stretch;
    gap: 16px;
  }
}

.col-left {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 16px;
  height: 100%;

  // Left-align the comic reader within its column instead of the
  // page-wide auto-centering used when the reader is the sole column.
  :deep(.comic-viewport),
  :deep(.scroll-comic-layout),
  :deep(.reader-controls),
  :deep(.sidebar-soundtrack-card) {
    margin-left: 0;
    margin-right: 0;
    max-width: 100%;
    width: 100%;
  }
}

.col-right {
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 16px;

  @media (min-width: 1024px) {
    height: 100%;
  }
}

// Persistent Floating Soundtrack Widget (markup moved to WolvesSoundtrack component)
// Mobile: reserve space at the bottom of the page for the fixed player bar,
// but only while the bar is actually visible (class toggled by WolvesSoundtrack).
:global(.wolves-player-active) .wolves-layout {
  @media (max-width: 767px) {
    padding-bottom: calc(88px + env(safe-area-inset-bottom));
  }
}

// Hero Section
.wolves-hero {
  display: flex;
  flex-direction: column;
  gap: 20px;
  padding: 24px 0 20px;
  border-bottom: 1px solid rgba(var(--color-blue-rgb), 0.2);

  .hero-text {
    text-align: center;

    @media (min-width: 768px) {
      text-align: left;
    }
  }

  .hero-title {
    font-size: clamp(2.8rem, 4.8vw, 4.2rem);
    font-weight: 800;
    letter-spacing: -0.03em;
    line-height: 1.1;
    text-transform: uppercase;
    margin-bottom: 12px;

    @media (min-width: 768px) {
      font-size: clamp(3.8rem, 5.8vw, 5.2rem);
    }

    .accent {
      color: var(--color-blue);
    }
  }

  .hero-description {
    font-size: 1.3rem;
    line-height: 1.6;
    color: #bdbdbd;
    margin-bottom: 12px;
    max-width: 600px;
  }

  .hero-footnote {
    font-size: 1rem;
    color: rgba(189, 189, 189, 0.6);
    font-style: italic;
  }
}

@keyframes pulse {
  0% {
    transform: scale(1);
    opacity: 0.8;
  }
  50% {
    transform: scale(1.1);
    opacity: 1;
  }
  100% {
    transform: scale(1);
    opacity: 0.8;
  }
}

.dispatch-quote-section {
  @media (min-width: 1024px) {
    flex: 1;
    display: flex;
    flex-direction: column;
  }
}

// Intercepted communications section
.dispatch-quote-card {
  background-color: #10151f;
  border: 1px solid #272727;
  padding: 16px;
  border-radius: 16px;
  display: flex;
  flex-direction: column;
  gap: 16px;
  position: relative;
  width: 100%;
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.3);
  transition:
    border-color 0.3s,
    box-shadow 0.3s;

  @media (min-width: 1024px) {
    flex: 1;
  }

  &:hover {
    border-color: rgba(var(--color-blue-rgb), 0.4);
    box-shadow: 0 10px 25px rgba(0, 0, 0, 0.3);
  }
}

.dispatch-plan-content {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  background: linear-gradient(180deg, rgba(16, 21, 31, 0.98) 0%, rgba(12, 16, 22, 0.98) 100%);
  border: 1px solid rgba(var(--color-blue-rgb), 0.22);
  border-radius: 10px;
  padding: 12px 14px;
  box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.05);

  @media (min-width: 480px) {
    padding-right: 192px;
  }
}

.dispatch-plan-command {
  margin: 0 0 6px;
  font-size: 0.86rem;
  color: rgba(189, 189, 189, 0.65);
}

.dispatch-plan-content .title-h2 {
  margin: 0;
  font-size: 1.2rem;
  letter-spacing: 0.03em;
  text-transform: uppercase;
  color: #ffffff;
}

.dispatch-plan-content .title-p {
  margin: 6px 0 0;
  font-size: 0.9rem;
  line-height: 1.5;
  color: rgba(189, 189, 189, 0.9);
}

.quote-viewport {
  position: relative;
  @media (min-width: 1024px) {
    flex: 1;
  }
}

.conversation-rotator {
  position: relative;
  padding-top: 4px;
  padding-right: 4px;
}

.conversation-heading {
  display: flex;
  justify-content: space-between;
  gap: 12px;
  border-bottom: 1px solid rgba(var(--color-blue-rgb), 0.25);
  padding-bottom: 8px;
  color: var(--color-blue-light);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 0.95rem;
  letter-spacing: 0.08em;
}

.conversation-title {
  margin: 16px 0 20px;
  color: #ffffff;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 1.35rem;
  letter-spacing: 0.04em;
  text-transform: uppercase;
}

.conversation-messages {
  display: flex;
  flex-direction: column;
  gap: 20px;
  list-style: none;
  margin: 0;
  padding: 0;
}

.conversation-message {
  border-left: 2px solid rgba(var(--color-blue-rgb), 0.45);
  padding-left: 16px;
}

.conversation-message-header {
  display: flex;
  justify-content: space-between;
  gap: 12px;
  color: var(--color-blue);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 0.95rem;
  letter-spacing: 0.06em;
}

.conversation-message-header time {
  color: rgba(189, 189, 189, 0.65);
}

.conversation-message p {
  margin: 6px 0 0;
  color: rgba(255, 255, 255, 0.9);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 1.15rem;
  line-height: 1.65;
}

.conversation-source {
  display: flex;
  flex-direction: column;
  gap: 4px;
  border-top: 1px solid rgba(var(--color-blue-rgb), 0.25);
  margin-top: 20px;
  padding-top: 12px;
  color: rgba(189, 189, 189, 0.62);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 0.78rem;
  line-height: 1.45;
}

.conversation-source a {
  color: var(--color-blue);
  text-decoration: underline;
  text-decoration-color: rgba(var(--color-blue-rgb), 0.4);
  text-underline-offset: 3px;
}

.conversation-source a:hover {
  color: var(--color-blue-light);
}

.lore-quote {
  min-height: 220px;
  padding: 8px 0 0;
}

.lore-quote-mark {
  color: rgba(var(--color-blue-rgb), 0.28);
  font-family: Georgia, serif;
  font-size: 5rem;
  line-height: 0.6;
  pointer-events: none;
  user-select: none;
}

.lore-quote-text {
  margin: 18px 0 24px;
  color: #ffffff;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 1.25rem;
  font-style: italic;
  line-height: 1.65;
}

.lore-quote-meta {
  display: flex;
  flex-direction: column;
  gap: 5px;
  border-top: 1px solid rgba(var(--color-blue-rgb), 0.25);
  padding-top: 14px;
  color: rgba(189, 189, 189, 0.78);
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-size: 0.95rem;
  line-height: 1.45;
}

.lore-quote-meta strong {
  color: var(--color-blue);
  font-size: 1rem;
}

.lore-quote-meta time {
  color: rgba(189, 189, 189, 0.6);
}

.quote-nav {
  display: flex;
  gap: 8px;
  z-index: 3;

  @media (max-width: 479px) {
    position: static;
    margin-bottom: 12px;
    justify-content: flex-end;
  }

  @media (min-width: 480px) {
    position: absolute;
    top: 24px;
    right: 24px;
  }
}

.quote-nav-btn {
  width: 44px;
  height: 44px;
  border-radius: 999px;
  border: 1px solid rgba(var(--color-blue-rgb), 0.45);
  background-color: #10151f;
  color: var(--color-blue-light);
  font-size: 1.4rem;
  line-height: 1;
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  transition: all 0.2s ease;

  &:hover {
    background-color: rgba(var(--color-blue-rgb), 0.15);
    border-color: var(--color-blue-light);
    color: #ffffff;
  }
}

/* Communication transition effects */
.quote-fade-enter-active,
.quote-fade-leave-active {
  transition: opacity 0.5s ease-in-out;
}

.quote-fade-leave-active {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
}

.quote-fade-enter-from,
.quote-fade-leave-to {
  opacity: 0;
}

// Support / QR Section
.support-wrap {
  text-align: center;
  max-width: 600px;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.qr-grid {
  display: flex;
  flex-direction: column;
  gap: 24px;
  max-width: 640px;
  margin: 24px auto 0;
  width: 100%;

  @media (min-width: 600px) {
    flex-direction: row;
  }
}

.qr-card {
  flex: 1;
  background-color: #10151f;
  border: 1px solid #272727;
  padding: 24px;
  border-radius: 16px;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 24px;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);

  .qr-title {
    font-size: 1.4rem;
    font-weight: 800;
    text-transform: uppercase;
    color: #ffffff;
    margin: 0;
  }

  .qr-image-box {
    width: 192px;
    height: 192px;
    background-color: #0c1016;
    border: 1px solid #272727;
    border-radius: 12px;
    padding: 16px;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: transform 0.3s;

    &:hover {
      transform: scale(1.05);
    }

    img {
      width: 100%;
      height: 100%;
      object-fit: contain;
    }
  }

  .qr-action-wrap {
    display: flex;
    flex-direction: column;
    gap: 8px;
    width: 100%;
    align-items: center;
  }

  .qr-btn {
    display: inline-block;
    color: #ffffff;
    font-weight: 700;
    font-size: 1.1rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    padding: 8px 24px;
    border-radius: 20px;
    text-decoration: none;
    transition: background-color 0.2s;

    &.blue {
      background-color: var(--color-blue);
      &:hover {
        background-color: var(--color-blue-light);
      }
    }

    &.dark {
      background-color: #272727;
      &:hover {
        background-color: #1e1e1e;
      }
    }
  }

  .qr-domain {
    font-size: 1.1rem;
    color: #616161;
  }
}

/* Share Button */
.quote-nav-btn.share-btn {
  width: auto;
  min-width: 68px;
  padding: 0 12px;
  font-size: 0.85rem;
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
  font-weight: bold;
}

/* Helper Utilities */
.font-mono {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace;
}
.text-cyan {
  color: var(--color-blue-light);
}
.text-gray {
  color: #888888;
}

/* Decryption Status Meter */
.decryption-meter-card {
  background-color: #10151f;
  border: 1px solid #272727;
  padding: 20px;
  border-radius: 16px;
  margin-top: 16px;
  display: flex;
  flex-direction: column;
  gap: 12px;
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.4);

  .meter-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-size: 0.85rem;
    letter-spacing: 0.05em;
  }

  .meter-title {
    color: #888888;
  }

  .meter-percentage {
    color: var(--color-blue-light);
    font-weight: bold;
  }

  .meter-bar-container {
    height: 6px;
    background-color: #0c1016;
    border-radius: 3px;
    overflow: hidden;
    border: 1px solid #1e1e1e;
  }

  .meter-bar-fill {
    height: 100%;
    background: linear-gradient(90deg, var(--color-blue), var(--color-blue-light));
    border-radius: 3px;
    box-shadow: 0 0 8px rgba(var(--color-blue-rgb), 0.5);
  }

  .meter-details {
    font-size: 0.75rem;
    color: #616161;
    margin: 0;
  }
}

/* Community & Conversion Section */
.community-console-grid {
  display: flex;
  flex-direction: column;
  gap: 24px;
  max-width: 900px;
  margin: 32px auto 0;
  width: 100%;

  @media (min-width: 768px) {
    flex-direction: row;
  }
}

.terminal-console-card,
.discord-invite-card {
  flex: 1;
  background-color: #10151f;
  border: 1px solid #272727;
  border-radius: 16px;
  box-shadow: 0 10px 30px rgba(0, 0, 0, 0.4);
  overflow: hidden;
}

/* Terminal Console Styling */
.terminal-console-card {
  display: flex;
  flex-direction: column;

  .console-header {
    background-color: #0c1016;
    border-bottom: 1px solid #272727;
    padding: 6px 12px;
    display: flex;
    align-items: center;
    justify-content: space-between;
  }

  .gnome-window-controls {
    display: flex;
    gap: 6px;
    align-items: center;
  }

  .gnome-control-btn {
    background: transparent;
    border: none;
    color: #5d5d5d;
    width: 24px;
    height: 24px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    transition: all 0.2s ease;
    padding: 0;

    &:hover {
      background-color: rgba(255, 255, 255, 0.08);
      color: #eeeeee;
    }

    &.close:hover {
      background-color: #e81123;
      color: #ffffff;
    }
  }

  .console-title {
    font-size: 0.8rem;
    color: #888888;
    text-align: left;
    flex-grow: 1;
  }

  .console-body {
    padding: 20px;
    display: flex;
    flex-direction: column;
    gap: 10px;
    flex-grow: 1;
  }

  .console-text {
    font-size: 0.9rem;
    margin: 0;
    line-height: 1.4;
  }

  .console-form {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-top: 10px;
    background-color: #0c1016;
    border: 1px solid #272727;
    border-radius: 8px;
    padding: 6px 12px;

    &:focus-within {
      border-color: var(--color-blue);
      box-shadow: 0 0 8px rgba(var(--color-blue-rgb), 0.25);
    }
  }

  .console-prompt {
    color: var(--color-blue);
    font-weight: bold;
    user-select: none;
  }

  .console-input {
    flex-grow: 1;
    background: transparent;
    border: none;
    outline: none;
    color: #ffffff;
    font-size: 0.9rem;
    width: 100%;

    &::placeholder {
      color: #424242;
    }
  }

  .console-submit-btn {
    background: transparent;
    border: none;
    color: var(--color-blue-light);
    font-weight: bold;
    cursor: pointer;
    font-size: 0.85rem;
    padding: 4px 8px;
    border-radius: 4px;
    transition: all 0.2s ease;

    &:hover {
      background-color: rgba(var(--color-blue-rgb), 0.15);
      color: #ffffff;
    }

    &:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }
  }

  .console-feedback {
    font-size: 0.85rem;
    color: var(--color-blue-light);
    margin-top: 6px;

    &.success {
      color: #27c93f;
    }
  }
}

/* Discord Invite Node Styling */
.discord-invite-card {
  padding: 24px;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  gap: 16px;

  .discord-title {
    font-size: 1.1rem;
    font-weight: bold;
    color: var(--color-blue-light);
    margin: 0;
  }

  .discord-desc {
    font-size: 0.95rem;
    color: #bdbdbd;
    line-height: 1.5;
    margin: 0;
  }

  .discord-action-wrap {
    display: flex;
    flex-direction: column;
    gap: 8px;
    margin-top: auto;
  }

  .discord-btn {
    display: block;
    text-align: center;
    background: linear-gradient(135deg, #5865f2, #4752c4);
    color: #ffffff;
    font-weight: 700;
    font-size: 1rem;
    text-transform: uppercase;
    letter-spacing: 0.05em;
    padding: 12px 24px;
    border-radius: 8px;
    text-decoration: none;
    transition: all 0.2s ease;
    box-shadow: 0 4px 12px rgba(88, 101, 242, 0.3);

    &:hover {
      background: linear-gradient(135deg, #6c79ff, #5865f2);
      box-shadow: 0 6px 16px rgba(88, 101, 242, 0.4);
      transform: translateY(-1px);
    }
  }

  .discord-coords {
    font-size: 0.75rem;
    color: #616161;
    text-align: center;
  }
}

/* Support Sub-footer Links */
.support-links {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 16px;
  margin-top: 32px;
  font-size: 0.9rem;

  a {
    color: #888888;
    text-decoration: none;
    transition: color 0.2s ease;

    &:hover {
      color: var(--color-blue-light);
    }
  }

  .separator {
    color: #424242;
    user-select: none;
  }
}

/* Experience Entrance CTA Styling */
.experience-cta-wrap {
  margin: 24px 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;

  @media (min-width: 768px) {
    align-items: flex-start;
  }
}

.experience-cta-btn {
  background: linear-gradient(135deg, rgba(66, 133, 244, 0.15), rgba(102, 179, 255, 0.25));
  border: 1px solid rgba(102, 179, 255, 0.4);
  color: #ffffff;
  padding: 14px 28px;
  font-size: 1.1rem;
  font-weight: bold;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.3s ease;
  box-shadow: 0 0 15px rgba(66, 133, 244, 0.1);
  letter-spacing: 0.05em;

  &:hover {
    background: linear-gradient(135deg, rgba(102, 179, 255, 0.25), rgba(125, 211, 252, 0.35));
    border-color: #7dd3fc;
    box-shadow: 0 0 25px rgba(66, 133, 244, 0.3);
    transform: translateY(-1px);
  }

  &:active {
    transform: translateY(1px);
  }
}

.experience-cta-sub {
  font-size: 0.8rem;
  color: #888888;
  letter-spacing: 0.1em;
}

/* Immersive Experience Active State */
.wolves-teaser-page.immersive-experience-active {
  overflow: hidden;
  height: 100vh;
  width: 100vw;
}

/* Immersive Fullscreen Dashboard */
.immersive-layout {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  z-index: 100;
  background-color: rgba(12, 16, 22, 0.85);
  backdrop-filter: blur(8px);
  display: flex;
  flex-direction: column;
  box-sizing: border-box;
  overflow: hidden;
}

/* Immersive Top Header HUD */
.immersive-hud-header {
  height: 60px;
  border-bottom: 1px solid rgba(102, 179, 255, 0.2);
  background: rgba(16, 21, 31, 0.5);
  padding: 0 24px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-shrink: 0;

  .hud-left {
    display: flex;
    align-items: center;
    gap: 10px;
    font-size: 0.9rem;
    font-weight: bold;
    color: #e2e8f0;
    letter-spacing: 0.05em;
  }

  .hud-indicator-dot {
    width: 8px;
    height: 8px;
    border-radius: 50%;
    background-color: #27c93f;
    box-shadow: 0 0 10px #27c93f;
  }

  .hud-exit-btn {
    background: transparent;
    border: 1px solid rgba(248, 113, 113, 0.4);
    color: rgba(248, 113, 113, 0.9);
    padding: 8px 16px;
    font-size: 0.85rem;
    font-weight: bold;
    border-radius: 6px;
    cursor: pointer;
    transition: all 0.2s ease;

    &:hover {
      background: rgba(248, 113, 113, 0.1);
      border-color: #f87171;
      color: #ffffff;
      box-shadow: 0 0 15px rgba(248, 113, 113, 0.25);
    }
  }
}

/* Immersive Middle Content (2fr 1fr) */
.immersive-content-grid {
  flex: 1;
  display: grid;
  grid-template-columns: 2fr 1fr;
  align-items: stretch;
  gap: 24px;
  padding: 24px;
  min-height: 0; /* Important for flex-child scrolling */
  box-sizing: border-box;

  @media (max-width: 1023px) {
    grid-template-columns: 1fr;
    grid-template-rows: 3fr 2fr;
    gap: 16px;
    padding: 16px;
  }
}

.immersive-col-left {
  min-width: 0;
  display: flex;
  flex-direction: column;
  height: 100%;

  :deep(#comic-reader) {
    height: 100% !important;
    display: flex;
    flex-direction: column;
    justify-content: center;
    margin: 0;
    max-width: 100%;
    padding: 0;
  }

  :deep(.page-flip-comic-layout) {
    height: 100%;
    display: flex;
    flex-direction: column;
    justify-content: space-between;
    gap: 12px;
  }

  :deep(.comic-viewport) {
    flex: 1;
    max-height: calc(100vh - 240px);
    width: 100%;
    max-width: 100%;
    border-color: rgba(102, 179, 255, 0.35);
  }
}

.immersive-col-right {
  min-width: 0;
  height: 100%;
  display: flex;
  flex-direction: column;
  overflow: hidden;

  :deep(.dispatch-quote-section) {
    height: 100% !important;
    display: flex;
    flex-direction: column;
  }

  :deep(.dispatch-quote-card) {
    height: 100% !important;
    display: flex;
    flex-direction: column;
    overflow: hidden;
  }

  :deep(.quote-viewport) {
    flex: 1;
    overflow-y: auto;
    /* Custom thin scrollbar */
    &::-webkit-scrollbar {
      width: 4px;
    }
    &::-webkit-scrollbar-track {
      background: transparent;
    }
    &::-webkit-scrollbar-thumb {
      background: rgba(102, 179, 255, 0.2);
      border-radius: 2px;
    }
    &::-webkit-scrollbar-thumb:hover {
      background: rgba(102, 179, 255, 0.4);
    }
  }
}

/* Immersive Bottom HUD Footer */
.immersive-hud-footer {
  height: 96px;
  border-top: 1px solid rgba(102, 179, 255, 0.2);
  background: rgba(16, 21, 31, 0.6);
  padding: 0 24px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 24px;
  flex-shrink: 0;

  @media (max-width: 767px) {
    height: auto;
    padding: 16px;
    flex-direction: column;
    gap: 16px;
  }
}

/* Mascot Telemetry Circle Console */
.mascot-console-hud {
  display: flex;
  align-items: center;
  gap: 12px;
  flex-shrink: 0;

  @media (max-width: 767px) {
    align-self: flex-start;
  }

  .mascot-console-ring {
    position: relative;
    width: 64px;
    height: 64px;
    border-radius: 50%;
    border: 1px solid rgba(102, 179, 255, 0.45);
    background: #090d16;
    padding: 2px;
    box-sizing: border-box;
    display: flex;
    align-items: center;
    justify-content: center;
    box-shadow: 0 0 10px rgba(102, 179, 255, 0.15);
  }

  .mascot-display-area {
    width: 100%;
    height: 100%;
    border-radius: 50%;
    overflow: hidden;
    position: relative;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .mascot-avatar {
    width: 100%;
    height: 100%;
    object-fit: cover;
    position: absolute;
    top: 0;
    left: 0;
    transition: opacity 1s ease-in-out;

    &.fading-out {
      opacity: 0;
    }
    &.fading-in {
      animation: mascotFadeIn 1s ease-in-out forwards;
    }
  }

  .hud-ring-overlay {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    border-radius: 50%;
    box-shadow: inset 0 0 8px rgba(0, 0, 0, 0.8);
    pointer-events: none;
  }

  .mascot-telemetry-text {
    display: flex;
    flex-direction: column;
    font-size: 0.75rem;
    font-weight: bold;
    letter-spacing: 0.05em;
    color: #94a3b8;
    line-height: 1.3;
  }
}

@keyframes mascotFadeIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

/* Soundtrack Dock Row Customization */
.immersive-soundtrack-dock {
  flex: 1;
  max-width: 680px;

  @media (max-width: 767px) {
    width: 100%;
  }
}

/* Scoped override styles within immersive mode footer */
.immersive-hud-footer {
  :deep(.sidebar-soundtrack-card) {
    background: transparent !important;
    border: none !important;
    box-shadow: none !important;
    padding: 0 !important;
    width: 100%;

    .soundtrack-panel {
      background: transparent !important;
      border: none !important;
      box-shadow: none !important;
      overflow: visible !important;
      display: flex;
      flex-direction: row;
      align-items: center;
      justify-content: center;
      gap: 16px;
      width: 100%;
    }

    .soundtrack-panel-main {
      padding: 0 !important;
      display: flex !important;
      flex-direction: row !important;
      align-items: center !important;
      justify-content: space-between !important;
      gap: 24px !important;
      width: 100%;

      @media (max-width: 900px) {
        grid-template-columns: auto 1fr auto !important;
        align-items: center !important;
      }
    }

    .soundtrack-artwork-shell,
    .soundtrack-lyrics-panel,
    .soundtrack-status,
    .soundtrack-links,
    .soundtrack-label,
    .soundtrack-mobile-bar {
      display: none !important;
    }

    .soundtrack-copy {
      display: flex !important;
      flex-direction: column !important;
      gap: 2px !important;
      text-align: left !important;
      flex: 1 !important;
      min-width: 0 !important;
    }

    .soundtrack-title {
      font-size: 0.95rem !important;
      font-weight: bold !important;
      margin: 0 !important;
      white-space: nowrap !important;
      overflow: hidden !important;
      text-overflow: ellipsis !important;
    }

    .soundtrack-artist {
      font-size: 0.75rem !important;
      color: rgba(102, 179, 255, 0.8) !important;
      margin: 0 !important;
    }

    .soundtrack-controls-group {
      display: flex !important;
      flex-direction: row !important;
      align-items: center !important;
      gap: 8px !important;
      margin: 0 !important;
      flex-shrink: 0 !important;
    }

    .quote-nav-btn {
      width: 36px !important;
      height: 36px !important;
      font-size: 1.1rem !important;
    }

    .soundtrack-action {
      min-height: 36px !important;
      height: 36px !important;
      padding: 0 16px !important;
      font-size: 0.8rem !important;
    }
  }
}

/* Right Telemetry Column */
.hud-right-telemetry {
  display: flex;
  flex-direction: column;
  gap: 6px;
  align-items: flex-end;
  text-align: right;
  flex-shrink: 0;

  @media (max-width: 767px) {
    align-self: flex-end;
  }

  .decryption-mini-meter {
    width: 140px;
    display: flex;
    flex-direction: column;
    gap: 4px;
  }

  .meter-header-mini {
    display: flex;
    justify-content: space-between;
    font-size: 0.65rem;
    font-weight: bold;
    color: #888888;
  }

  .meter-bar-mini {
    height: 3px;
    background-color: #0c1016;
    border-radius: 1.5px;
    overflow: hidden;
    border: 1px solid rgba(102, 179, 255, 0.1);
  }

  .meter-fill-mini {
    height: 100%;
    width: 7%;
    background-color: #66b3ff;
    border-radius: 1.5px;
    box-shadow: 0 0 6px rgba(102, 179, 255, 0.5);
  }

  .hud-telemetry-coords {
    font-size: 0.68rem;
    font-weight: bold;
    color: #616161;
    letter-spacing: 0.05em;
  }
}

/* Custom Fast Pulse Utility */
.animate-pulse-fast {
  animation: pulseFast 1.2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
}

@keyframes pulseFast {
  0%,
  100% {
    opacity: 1;
  }
  50% {
    opacity: 0.35;
  }
}
</style>
